### ISSUE TITLE
CLI: License & Versioning

### ISSUE THREAD

**Issue by t-kelly** [archetype-themes/plugin-theme-component#332]
**Current Situation**
- We need a way of knowing what version of components are installed
- When things go public, the license needs to be included wherever the code may be used

**Proposed solution**
1. Search for LICENSE.md and if found prepend it to all files
2. Include component release version as a prepend so we know what version of the file we're dealing with inside of the theme

**Comment by fleveillee** [comment]
Resolved with release 3.5.0
